<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
	<ApplicationIcon>cantio.ico</ApplicationIcon>
	<Version>1.44</Version>
	<RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\Grenze-Light.ttf" />
    <None Remove="Assets\Fonts\Grenze-Regular.ttf" />
    <None Remove="Assets\Fonts\Grenze-Medium.ttf" />
    <None Remove="Assets\Fonts\Grenze-SemiBold.ttf" />
    <None Remove="Assets\Fonts\Grenze-Bold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\SofiaSansExtraCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\SofiaSansExtraCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\SofiaSansExtraCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\Lato-Light.ttf" />
    <None Remove="Assets\Fonts\Lato-Regular.ttf" />
    <None Remove="Assets\Fonts\Lato-Bold.ttf" />
    <None Remove="cantio.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
<PackageReference Include="WpfScreenHelper" Version="2.1.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Data\psalmy.json.gz" />
  </ItemGroup>

  <ItemGroup>
	<Resource Include="Assets\Fonts\Grenze-Light.ttf" />
	<Resource Include="Assets\Fonts\Grenze-Regular.ttf" />
	<Resource Include="Assets\Fonts\Grenze-Medium.ttf" />
	<Resource Include="Assets\Fonts\Grenze-SemiBold.ttf" />
	<Resource Include="Assets\Fonts\Grenze-Bold.ttf" />
	<Resource Include="Assets\Fonts\BarlowSemiCondensed-Regular.ttf" />
	<Resource Include="Assets\Fonts\BarlowSemiCondensed-Bold.ttf" />
	<Resource Include="Assets\Fonts\BarlowSemiCondensed-Italic.ttf" />
	<Resource Include="Assets\Fonts\BarlowSemiCondensed-BoldItalic.ttf" />
	<Resource Include="Assets\Fonts\SofiaSansExtraCondensed-Regular.ttf" />
	<Resource Include="Assets\Fonts\SofiaSansExtraCondensed-Bold.ttf" />
	<Resource Include="Assets\Fonts\SofiaSansExtraCondensed-Italic.ttf" />
	<Resource Include="Assets\Fonts\Lato-Light.ttf" />
	<Resource Include="Assets\Fonts\Lato-Regular.ttf" />
	<Resource Include="Assets\Fonts\Lato-Bold.ttf" />
	<Resource Include="cantio.ico" />
  </ItemGroup>

</Project>
