server {
    listen 443 ssl;
    server_name cantio.app www.cantio.app;

    root /var/www/cantio-landing;
    index index.html;

    ssl_certificate     /etc/letsencrypt/live/cantio.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cantio.app/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name cantio.app www.cantio.app;
    return 301 https://$host$request_uri;
}
