<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\Cinzel-Bold.ttf" />
    <None Remove="Assets\Fonts\Cinzel-Regular.ttf" />
    <None Remove="Assets\Fonts\Cinzel-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.WindowsAPICodePack-Shell" Version="1.1.0" />
    <PackageReference Include="WpfScreenHelper" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
	<Resource Include="Assets\Fonts\Cinzel-Bold.ttf" />
	<Resource Include="Assets\Fonts\Cinzel-Regular.ttf" />
	<Resource Include="Assets\Fonts\Cinzel-SemiBold.ttf" />
  </ItemGroup>

</Project>
